apiVersion: apps/v1
kind: Deployment
metadata:
  name: esewa-app
  namespace: esewa-namespace
  labels:
    app: esewa-app
    env: production
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: esewa-app
  template:
    metadata:
      labels:
        app: esewa-app
      annotations:
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/json.message_key: "message"
        co.elastic.logs/json.ignore_decoding_error: "true"
    spec:
      securityContext:
        runAsNonRoot: false
        # runAsUser: 1000
      # THIS IS THE CORRECT LEVEL (Inside spec, outside containers)
      terminationGracePeriodSeconds: 60 
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: esewa-app
        image: sudarshanuprety/esewa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-primary.esewa-namespace.svc.cluster.local:5432/esewadb"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-password
        - name: DB_READ_URL
          value: "jdbc:postgresql://postgres-read.esewa-namespace.svc.cluster.local:5432/esewadb"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms256m -Xmx768m -XX:+UseG1GC -XX:MaxMetaspaceSize=256m"
        # livenessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        #   timeoutSeconds: 5