apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esewa-ingress
  namespace: esewa-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-rps: "300"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
spec:
  tls:
  - hosts:
    - esewaprod.sudarshan-uprety.com.np
    secretName: esewa-prod-tls
  rules:
  - host: esewaprod.sudarshan-uprety.com.np
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: esewa-service
            port:
              number: 80