apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: esewa-namespace
spec:
  serviceName: "postgres-primary"
  replicas: 6
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      imagePullSecrets:
      - name: dockerhub-secret
      initContainers:
      - name: volume-permissions
        image: bitnami/postgresql:latest
        command: ["/bin/sh", "-c", "chown -R 1001:1001 /bitnami/postgresql"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
      containers:
      - name: postgresql
        image: bitnami/postgresql:latest
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: POSTGRESQL_REPLICATION_USER
          value: "repl_user"
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: replication-password
        - name: POSTGRESQL_MASTER_HOST
          value: "postgres-0.postgres-primary.esewa-namespace.svc.cluster.local"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-name
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-user
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        command:
        - /bin/bash
        - -c
        - |
          if [[ $HOSTNAME == "postgres-0" ]]; then
            export POSTGRESQL_REPLICATION_MODE=master
          else
            export POSTGRESQL_REPLICATION_MODE=slave
          fi
          /opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
