apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: esewa-namespace
type: Opaque
stringData:
  postgres-password: "postgrespassword"
  replication-password: "replicationpassword"
  database-name: "esewadb"
  database-user: "esewauser"
  database-password: "esewapassword"
